name: C# types

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-csharp-types:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: csharp

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion

      - name: Set tag to version  
        run: dotnet TagToVersion -t ${{ github.ref }} -f DataContracts/Directory.Build.props

      - name: Build NuGet package
        run: dotnet pack --configuration Release

      - name: Push package
        run: dotnet nuget push DataContracts/bin/Release/Podkrepibg.DataContracts.*.nupkg -k ${{ secrets.DEPLOY_TYPES_PACKAGE_TOKEN }} -s https://nuget.pkg.github.com/podkrepi-bg/index.json