name: Go types

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "protos/**"

jobs:
  check_go_types:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/podkrepi-bg/go-devcontainer:v1.0.0
    steps:
      - uses: actions/checkout@v2

      - name: Install protoc
        run: apk --no-cache add curl git protoc=3.13.0-r2 protobuf-dev

      - name: Install Go proto tooling
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Generate Go types
        run: task build_go_types

      - name: Check if Go types are outdated
        run: git diff --exit-code --name-!only